travis:
  secure:
    BINSTAR_TOKEN: IH172ElN6gj80g5vLUioBS3DnPYOBih0fdXLW7GlK6o3/lZtTKBsJpRUR7zF1JG/sU7l8suH9D1ZerYw5iOTCXDXubBKx/d4z6UFATlb/eK4C1jbA3WLR1FK5eNkEq1KtsxiBhwyDg+v4Y0DG3nWPahXV3AxKSV4+ARBveeayTfXo8YbSd+luAYxYeaZVIkVu7HxXUMKA22lLwK5uaBVlE8TZBECuiX00S64Dj+fLxO5BWnSMP+eFRL26fJlf406iwfB5YYHSw+XDwmn6NZfLrrAg9CDMgj+hFHXdPZaG7VUrPpbU4LneGCEZ7Y/FFbKTHqdyLfpfAph48vWQFGDP5KGVWLrfTI3SnViBA8FC05n7/sjabIAD7lb/tmc/tYVlr9ICX6/0IcweXcbf5ElFl1HRc2MxXMymzF+jwuw3Vtoj80Qz77hynU6EVA2IXZSyLVXbh7xqSVsZtZjikpP0aNKmUW8I4r1dXIUORN694ajDOO97KZyZW9W92Hu1hVHf7jf7QfOGiv0DKE+kffhE86UCjymPdjXtF/2TlR9125+ojL9iyU0yIC1YQMs2Z+D768bXtyGcOBgL7QOqunXkLEzZvXoM6Or10ZnEz2ks/G927Pwa81CqhJgCQ7FuQy0A18f5uk+wAoKUO1jwL+QH9teMH+Z4o+/L6zt5W5cMzk=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
